[project]
name = "raspberry-temperature"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yacouba-kone", email = "40605115+yacouba-kone@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "adlfs>=2026.8.0",
    "azure-eventhub>=5.15.1",
    "azure-identity>=1.25.3",
    "azure-servicebus>=7.14.3",
    "azure-storage-blob>=12.30.3",
    "celery>=5.6.3",
    "duckdb>=1.5.5",
    "duckdb-engine>=0.17.0",
    "kedro>=1.6.0",
    "kedro-datasets>=9.6.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.0",
    "pandas>=3.0.5",
    "pyodbc>=5.3.0",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.52",
    "websocket-client>=1.9.2",
]

[project.scripts]
raspberry-temperature = "raspberry_temperature:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]

[tool.kedro] 
package_name = "raspberry_temperature" 
project_name = "raspberry-temperature" 
kedro_init_version = "1.6.0" 
source_dir = "src"
[tool.kedro_telemetry]
project_id = "85a49cb3a26f488fb8cd29fc0ffec2f3"
