[project]
name = "raspberry-temperature"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yacouba-kone", email = "40605115+yacouba-kone@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "mlflow>=3.16.0",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
raspberry-temperature = "raspberry_temperature:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
